# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.10+.
version: "2"
services:
  # Webapp
  webapp:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        python_version: "${PYTHON_VERSION}"
    image: local/pontoon_py${PYTHON_VERSION}
    env_file:
      - docker/config/webapp.env
    depends_on:
      - postgresql
    ports:
      - "35146:8000"
      - "35147:3000"
    volumes:
      - ./pontoon:/app/pontoon
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./tests:/app/tests
      - ./ssh:/home/pontoon/.ssh

  # Database
  postgresql:
    restart: always
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
    volumes:
      - ./data:/var/lib/postgresql/data
